#include <iostream>
#include <exception>
int main() { std::cout << sizeof(std::runtime_error) << std::endl; }
